### ISSUE TITLE
Iteration 1 - Responsibilities

### ISSUE THREAD

**Issue by JumboSchrimp** [praveenen24/3303#1]
Could I get a list of who did what for iteration 1? I'll need to put it in the readme.

**Comment by praveenen24** [comment]
Kari: Use Case Maps
Omar: UML Class Diagrams
Praveenen: Implemented Iteration #1 (Read and Write functionalities)
Dylan: Implemented Iteration 0
Calvin: Documentation

**Comment by praveenen24** [comment]
Also you also need to mention in the documentation that we started with my assignment1 code
